### PR TITLE
Forbidding empty natIPNames array

### LINKED ISSUE #480: Empty natIPNames list for cloudNAT configuration should be rejected
**How to categorize this issue?**

/area networking
/kind bug
/platform gcp

**What happened**:

We had a user ticket where the shoot.yaml contained the following configuration for the `cloudNAT`:
```
networks:
        cloudNAT:
          minPortsPerVM: 2048
          natIPNames: []
```

This configuration was not rejected and caused an error during the Shoot creation:
```
task "Waiting until shoot infrastructure has been reconciled" failed: Error while waiting for Infrastructure shoot--hc-dev--i067095-haas/i067095-haas to become ready: error during reconciliation: Error reconciling infrastructure: could not find all requested variables: [nat_ips]
```

**What you expected to happen**:

An empty list of `natIPNames` for `cloudNAT` should be rejected.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`): v1.22.11
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by AleksandarSavchev**
**How to categorize this PR?**

/area networking
/kind bug
/platform gcp

**What this PR does / why we need it**:
This PR fixes the `networks` validation to forbid configuring an empty `natIPNames` array in `networks.cloudNAT`

**Which issue(s) this PR fixes**:
Fixes #480

**Special notes for your reviewer**:

**Release note**:

```bugfix user
admission-gcp does no longer allow setting Shoot's `.spec.provider.infrastructureConfig.networks.cloudNAT.natIPNames` field to empty list.
```

### CODE REVIEW

File: pkg/controller/infrastructure/configvalidator.go [hunk 1]
```diff
@@ -76,7 +76,12 @@ func (c *configValidator) Validate(ctx context.Context, infra *extensionsv1alpha
 func (c *configValidator) validateNetworks(ctx context.Context, computeClient gcpclient.ComputeClient, clusterName, region string, networks api.NetworkConfig, fldPath *field.Path) field.ErrorList {
 	allErrs := field.ErrorList{}
 
-	if networks.CloudNAT == nil || len(networks.CloudNAT.NatIPNames) == 0 {
+	if networks.CloudNAT == nil {
+		return allErrs
+	}
+
+	if len(networks.CloudNAT.NatIPNames) == 0 {
```
Comment (ialidzhikov) [inline pkg/controller/infrastructure/configvalidator.go:83]: The validation should be rather part of `admission-gcp` - https://github.com/gardener/gardener-extension-provider-gcp/blob/37e1e2ca92132db555271ed286f8d3d337253085/pkg/apis/gcp/validation/infrastructure.go#L28 . 

This is to prevent created/updating Shoots with empty `networks.cloudNAT.natIPNames`.
The `ConfigValidator` validation is executed before Infrastructure reconciliation when the Shoot is already created/updated with the invalid spec. And the `ConfigValidator` was mainly introduced to allow validating resources using the cloud provider APIs as well. You can read more about the concept in https://github.com/gardener/gardener/blob/v1.58.0/docs/extensions/infrastructure.md#configvalidator-interface.

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

File: pkg/apis/gcp/validation/infrastructure.go [hunk 2]
```diff
@@ -124,6 +124,10 @@ func ValidateInfrastructureConfig(infra *apisgcp.InfrastructureConfig, nodesCIDR
 		}
 	}
 
+	if infra.Networks.CloudNAT != nil && len(infra.Networks.CloudNAT.NatIPNames) == 0 {
+		allErrs = append(allErrs, field.Forbidden(networksPath.Child("cloudNAT", "natIPNames"), "should not be empty array"))
```
Comment (ialidzhikov) [inline pkg/apis/gcp/validation/infrastructure.go:128]: Nit: we could use `field.Invalid` instead of `field.Forbidden`:

```suggestion
		allErrs = append(allErrs, field.Invalid(networksPath.Child("cloudNAT", "natIPNames"), infra.Networks.CloudNAT.NatIPNames, "nat IP names cannot be empty"))
```

File: pkg/apis/gcp/validation/infrastructure.go [hunk 3]
```diff
@@ -124,6 +124,10 @@ func ValidateInfrastructureConfig(infra *apisgcp.InfrastructureConfig, nodesCIDR
 		}
 	}
 
+	if infra.Networks.CloudNAT != nil && len(infra.Networks.CloudNAT.NatIPNames) == 0 {
```
Comment (ialidzhikov) [inline pkg/apis/gcp/validation/infrastructure.go:127]: Correct me if I am wrong but this validation will also start failing for valid InfrastructureConfig such as:
```yaml
networks:
  cloudNAT:
    minPortsPerVM: 2048
```

We should rather require at least 1 nat IP names to be provided **only** when the field is explicitly set to empty array.
We should not require at least 1 nat IP name to be provided **always** because the field is optional.

The check we need is:
```suggestion
	if infra.Networks.CloudNAT != nil && infra.Networks.CloudNAT.NatIPNames != nil && len(infra.Networks.CloudNAT.NatIPNames) == 0 {
```

because `len(nil)` is `0`.

Can you also add an unit test to cover this scenario?

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/squash
