### PR TITLE
Make admission check of min worker pool and number of zones backward compatible

### LINKED ISSUE #351: The worker validation prevents lifecycle operations from other controllers
**How to categorize this issue?**

/area ops-productivity quality robustness usability
/kind bug
/priority 2
/platform gcp

**What happened**:
I have a shoot cluster that is using a k8s versions that has expired long time ago. The shoot maintenance controller fails to update the shoot to the next k8s versions because the shoot have a worker pool configured with 3 availability but the minimum number of nodes is just 1, so each attempt to reconcile/maintain this shoot fails with 
```
Error syncing Shoot Maintenance garden-foo/bar admission webhook "validation.gcp.provider.extensions.gardener.cloud" denied the request: spec.provider.workers[0].minimum: Forbidden: minimum value must be >= 3 if maximum value > 0 (auto scaling to 0 & from 0 is not supported"
```

**What you expected to happen**:
Update requests not changing anything in the worker config to be allowed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
See https://github.com/gardener/gardener-extension-provider-gcp/pull/296#issuecomment-881450283

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.19.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area ops-productivity quality robustness usability
/kind bug
/platform gcp

**What this PR does / why we need it**:
Make admission check of min worker pool and number of zones backward compatible

**Which issue(s) this PR fixes**:
Fixes #351 

**Special notes for your reviewer**:

**Release note**:

```other operator
The admission webhook validating the minimum workers in a pool to be >= number of availability zones has been made backward compatible with shoot clusters that have been created before this admission check to be implemented.
```

### CODE REVIEW

File: pkg/apis/gcp/validation/shoot_test.go [hunk 1]
```diff
@@ -207,6 +207,90 @@ var _ = Describe("Shoot validation", func() {
...
+			}
+
+			oldWorkers := []core.Worker{}
+
+			errorList := ValidateWorkersUpdate(oldWorkers, newWorkers, workerPath)
+
+			Expect(errorList[0].Error()).To(Equal("spec.workers[0].minimum: Forbidden: spec.workers[0].minimum value must be >= " + fmt.Sprint(len(newWorkers[0].Zones)) + " (number of zones) if maximum value > 0 (auto scaling to 0 & from 0 is not supported)"))
+		})
+
+		It("should not return any error because existing worker pool does not honor having min workers >= number of zones", func() {
```
Comment (AxiomSamarth) [inline pkg/apis/gcp/validation/shoot_test.go:242]: Describing the test case more comprehensively

```suggestion
		It("mimicking upgrade scenario - should not return any error because new worker pool is same as the existing worker pool though the old worker pool does not honor having min workers >= number of zones", func() {
```

File: pkg/apis/gcp/validation/shoot.go [hunk 2]
```diff
@@ -84,22 +85,30 @@ func validateVolume(vol *core.Volume, fldPath *field.Path) field.ErrorList {
...
+
+		if found && validation.ShouldEnforceImmutability(newWorker.Zones, oldWorker.Zones) {
+			allErrs = append(allErrs, apivalidation.ValidateImmutableField(newWorker.Zones, oldWorker.Zones, workerFldPath.Child("zones"))...)
 		}
 
 		// TODO: This check won't be needed after generic support to scale from zero is introduced in CA
 		// Ongoing issue - https://github.com/gardener/autoscaler/issues/27
-		if err := ValidateWorkerAutoScaling(newWorker, workerFldPath.Child("minimum").String()); err != nil {
-			allErrs = append(allErrs, field.Forbidden(workerFldPath.Child("minimum"), err.Error()))
+		if !equality.Semantic.DeepEqual(newWorker, oldWorker) {
```
Comment (AxiomSamarth) [inline pkg/apis/gcp/validation/shoot.go:97]: This is a very nice, @vpnachev. I learnt this equality package newly today.

**Review by AxiomSamarth — APPROVED** [review]
/lgtm

File: pkg/apis/gcp/validation/shoot.go [hunk 3]
```diff
@@ -84,22 +85,30 @@ func validateVolume(vol *core.Volume, fldPath *field.Path) field.ErrorList {
...
-
 		workerFldPath := fldPath.Index(i)
-		for _, oldWorker := range oldWorkers {
-			if newWorker.Name == oldWorker.Name {
-				if validation.ShouldEnforceImmutability(newWorker.Zones, oldWorker.Zones) {
-					allErrs = append(allErrs, apivalidation.ValidateImmutableField(newWorker.Zones, oldWorker.Zones, workerFldPath.Child("zones"))...)
-				}
-				break
-			}
+		oldWorker, found := getWorkerByName(newWorker.Name, oldWorkers)
```
Comment (ialidzhikov) [inline pkg/apis/gcp/validation/shoot.go:89]: There is already a similar helper func in gardener/gardener - https://github.com/gardener/gardener/blob/f8f5ed365096290d5437b80d860b3d602499e9c8/pkg/apis/core/helper/helpers.go#L248-L256.

Would it be possible to reuse the existing helper func?

```suggestion
		oldWorker := helper.FindWorkerByName(oldWorkers, newWorker.Name)
```

**Review by ialidzhikov — COMMENTED** [review]
Generally lgtm. I have only 1 minor suggestion/question.

File: pkg/apis/gcp/validation/shoot.go (hunk 3 above)
Comment (vpnachev) [reply pkg/apis/gcp/validation/shoot.go]: Done.

/merge squash

**Review by ialidzhikov — APPROVED** [review]
/lgtm
